author = "Eko Cahyo"
baseurl = "https://ekocahyo.github.io/"
canonifyurls = true
copyright = "Copyright © 2020, Eko Cahyo Authors; all rights reserved."
paginate = 5
theme = "alageek"
title = "A Small Note"

[params]
copyright = "Created by Cahyo"
copyrightUrl = "https://ekocahyo.github.io"
description = "My Blog"
faviconfile = "cahyo.png"
latestpostcount = 15
logofile = "cahyo.png"
highlightjs = true
highlightjslanguages = [ "bash", "css", "diff", "django", "javascript", "python", "yaml" ]
toc = true
posts_navigation = true
progressively = true
# flattr = "?"
github = "ekocahyo"
# gitlab = "?"
# linkedin = "?"
telegram = "m_eko_cahyo_s"
# twitter = "?"
# mastodon_url = "https://mastodon.url/?"
email = "ekocahyo27@gmail.com"
mainSections = ["blog", "how-to"]

# [[params.best_posts]]
# title = "Migrate to Hugo from Jekyll"
# url = "/blog/migrate-from-jekyll/"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.primary]]
identifier = "how-to"
name = "How to"
url = "/how-to/"
weight = 20

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 30

[[menu.primary]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 40

[[menu.secondary]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 120

[[menu.secondary]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 110

#[[menu.footer]]
#identifier = "tags"
#name = "Tags"
#url = "/tags/"
#weight = 50
